server:
  port: 8480
spring:  
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          oidc:
            jwk-set-uri: http://mmfb.com/auth/realms/mmfb/protocol/openid-connect/certs
            issuer-uri: http://mmfb.com/auth/realms/mmfb
        registration:
          oidc:
            redirect-uri: "http://mmfb.com/app1/login/oauth2/code/{registrationId}"
            client-id: apiclient
            client-secret: web_app