version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.prometheus.rule: Host(`prometheus.mmfb.com`)
        traefik.http.middlewares.prometheus.headers.framedeny: "false"
        traefik.http.middlewares.prometheus.headers.sslredirect: "true"
        traefik.http.middlewares.prometheus.headers.contentsecuritypolicy: upgrade-insecure-requests
        traefik.http.middlewares.prometheus.headers.sslproxyheaders.x-forwarded-proto: https
        traefik.http.routers.prometheus.tls: "true"    
        traefik.http.routers.prometheus.middlewares: prometheus
        traefik.http.services.prometheus.loadbalancer.server.port: 9090
        traefik.http.services.prometheus.loadbalancer.passhostheader: "true"
        traefik.http.services.prometheus.loadbalancer.sticky.cookie: "true"
        traefik.http.services.prometheus.loadbalancer.sticky.cookie.name: "prometheus"  
#        traefik.http.middlewares.admin-prometheus.basicauth.users: admin:${HASHED_PASSWORD?Variable not set}
  
    # On MacOS, remove next line and replace localhost by host.docker.internal in prometheus/prometheus.yml and
    # grafana/provisioning/datasources/datasource.yml
    networks: 
     - traefik-public
  grafana:
    image: grafana/grafana:7.0.1
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.grafana.rule: Host(`grafana.mmfb.com`)
        traefik.http.middlewares.grafana.headers.framedeny: "false"
        traefik.http.middlewares.grafana.headers.sslredirect: "true"
        traefik.http.middlewares.grafana.headers.contentsecuritypolicy: upgrade-insecure-requests
        traefik.http.middlewares.grafana.headers.sslproxyheaders.x-forwarded-proto: https
        traefik.http.routers.grafana.tls: "true"    
        traefik.http.routers.grafana.middlewares: grafana
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        traefik.http.services.grafana.loadbalancer.passhostheader: "true"
        traefik.http.services.grafana.loadbalancer.sticky.cookie: "true"
        traefik.http.services.grafana.loadbalancer.sticky.cookie.name: "grafana"        
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in prometheus/prometheus.yml and
    # grafana/provisioning/datasources/datasource.yml
    networks: 
     - traefik-public
networks:
  traefik-public:
    external: true