server:
  port: 8580
spring:  
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
  security:
    oauth2:
      client:
        provider:
          oidc:
            jwk-set-uri: https://www.mmfb.com/auth/realms/mmfb/protocol/openid-connect/certs
            issuer-uri: https://www.mmfb.com/auth/realms/mmfb
        registration:
          oidc:
            redirect-uri: "https://www.mmfb.com/app2/login/oauth2/code/{registrationId}"
            client-id: apiclient
            client-secret: d4e0aa8f-4a4c-449e-b4fd-252bc8a227d1