global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    swarmmode: false

  file:
    filename: /etc/traefik/config.yml
    watch: true
  
  # consul:
  #   endpoints: 
  #    - "consul-leader:8500"
  #   rootkey: "traefik"
  #   tls:
  #    caOptional: true
  #    cert: /etc/certs/mmfb-cert.pem
  #    key: /etc/certs/mmfb-key.pem
  #    insecureSkipVerify: true
     
log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
