apiVersion: v1
kind: ServiceAccount
metadata:
 name: traefik-ingress-controller
 namespace: mmfb
---
apiVersion: v1
kind: Service
metadata:
  namespace: mmfb
  name: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: websecure
      port: 4443
      targetPort: 4443
  selector:
      app: traefik
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mmfb
  name: traefik
  labels:
    app: traefik
    traefik.enable: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          args:
            - --api.insecure
            - --accesslog
            - --log.level=DEBUG
            - --api.dashboard=true
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --providers.file.filename=/traefik/traefik.yml
            - --providers.file.watch=true
          volumeMounts:
            - name: config 
              mountPath: /traefik
                      
          securityContext:
            privileged: true        
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080  
      volumes:
        - name: config
          configMap:
            name: config-data
            # items:
            #   - key: traefik.yml
            #     path: /traefik/traefik.yml
            #   - key: mmfb-cert.pem
            #     path: /traefik/mmfb-cert.pem   
            #   - key: mmfb-key.pem
            #     path: /traefik/mmfb-key.pem                                         
      # volumes:
      #   - name: cert
      #     persistentVolumeClaim:
      #       claimName: cert-volume-claim-4
      #   - name: traefik
      #     persistentVolumeClaim:
      #       claimName: traefik-volume-claim-4
status: {}
--- 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin-route
  namespace: mmfb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.mmfb.kareegor.com`)
      kind: Rule
      services:
        - name: traefik
          port: 8080
  tls:
    -secretName: secret-tls

    