version: "3.3"
services:
  consul:
    image: consul:latest
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0
    networks: 
     - edge_default 
networks: 
  edge_default:
      external: true