version: "3.3"

services:
  service1:
      image: service1:latest 
      extra_hosts:
        - "www.mmfb.com:192.168.0.107" #add hostname to /etc/hosts file of docker
      environment:
        SPRING_CLOUD_CONSUL_HOST: consul-leader
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI: "https://www.mmfb.com/auth/realms/mmfb"
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_JWK_SET_URI: "https://www.mmfb.com/auth/realms/mmfb/protocol/openid-connect/certs"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_REDIRECT_URI: "https://www.mmfb.com/app1/login/oauth2/code/{registrationId}"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID: "apiclient"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET: "7169adfb-36d9-47ad-97c2-0889eb0fafc1"
      deploy:
       mode: replicated
       replicas: 2
       restart_policy:
          condition: on-failure
          max_attempts: 3
          window: 120s
       update_config:
          parallelism: 1
          failure_action: rollback 
      volumes:
       # Map the certificats into the container
       - ../certs:/etc/certs:ro
      networks:
        - traefik-public  
networks: 
  traefik-public:
      external: true